# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rack'
gem 'ougai'

group :test do
  gem 'rspec'
  gem 'rack-test'
end
