name         'puppetlabs-java'
version      '1.1.1'
source       'git://github.com/puppetlabs/puppetlabs-java'
author       'puppetlabs'
license      'Apache'
summary      'Manage the official Java runtime'
description  'Manage the official Java runtime'
project_page 'https://github.com/puppetlabs/puppetlabs-java'

dependency   'puppetlabs/stdlib', '>= 0.1.6'
