name    'elasticsearch-logstash'
version '0.5.1'
source 'https://github.com/elasticsearch/puppet-logstash'
author 'elasticsearch'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Logstash'
description 'Module for managing and configuring Logstash'
project_page 'https://github.com/elasticsearch/puppet-logstash'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'ispavailability/file_concat', '>= 0.1.0'
